FROM rust:1 as builder
WORKDIR /src
COPY ./src ./src
COPY ./Cargo.toml .
COPY ./Cargo.lock .
RUN cargo install --path .

FROM debian:bullseye-slim
RUN apt update && apt upgrade -y && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/todoblob-server /usr/local/bin/todoblob-server
CMD ["todoblob-server"]
