apiVersion: v1
kind: Service
metadata:
  namespace: todoblob
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: todoblob
data:
  redis.conf: |
    bind 0.0.0.0 ::1
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    loglevel notice
    logfile ""
    databases 1
    save 1800 1 60 100
    dir /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: todoblob
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 64Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todoblob
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      namespace: todoblob
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: redis:7
        command: [ "redis-server", "/config/redis.conf" ]
        volumeMounts:
        - name: redis-config
          mountPath: /config/
        - name: redis-data
          mountPath: /data/
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      - name: redis-data
        persistentVolumeClaim:
          claimName: data-pvc

