apiVersion: v1
kind: Service
metadata:
  namespace: todoblob
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todoblob
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      namespace: todoblob
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: registry.homep.qxczv.pw/todoblob-server:latest
        ports:
          - containerPort: 5000
        env:
          - name: RUST_LOG
            value: info
          - name: RUST_BACKTRACE
            value: "1"
          - name: ROCKET_ADDRESS
            value: "0.0.0.0"
          - name: ROCKET_PORT
            value: "5000"
          - name: REDIS_URL
            value: redis://db:6379/
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: todoblob
  name: todoblob-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - todoblob.homep.qxczv.pw
      secretName: todoblob-server-tls
  rules:
  - host: todoblob.homep.qxczv.pw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server
            port:
              number: 80
